routes/web.php
<?php

use \Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');

Route::post('/analytics/view', 'AnalyticsController@view')->name('analytics.view');

Route::get('contact', 'ContactController@general')->name('contact');
Route::get('contact/general', 'ContactController@general');
Route::post('contact', 'ContactController@post')->name('contact.post');

// ## Authentication
\Illuminate\Support\Facades\Auth::routes();
Route::get('login/{service}', 'Auth\SocialLoginController@redirect')->name('auth.social');
Route::get('login/{service}/callback', 'Auth\SocialLoginController@callback')->name('auth.social.callback');

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function() {
    Route::get('/settings', 'Users\PreferencesController@settings')->name('user.settings');
    Route::post('/settings', 'Users\PreferencesController@updateSettings')->name('user.settings.post');

    Route::get('/demographics', 'Users\PreferencesController@demographics')->name('user.demographics');
    Route::post('/demographics', 'Users\PreferencesController@saveDemographics')->name('user.demographics.post');

    Route::get('/notifications', 'NotificationController@all')->name('notifications');
    Route::post('/notifications/mark', 'NotificationController@mark')->name('notifications.mark');
    Route::delete('/notifications/delete', 'NotificationController@delete')->name('notifications.delete');
});

// ## Public Profiles
Route::group(['prefix' => 'u'], function() {
    Route::get('{handle?}', 'Users\ProfileController@profile')->name('profile');
    Route::get('{handle?}/rankings', 'Users\ProfileController@rankings')->name('profile.rankings');
});

// ## Tests
Route::group(['prefix' => 'tests'], function() {
    Route::get('/', 'TestController@index')->name('tests');
    Route::get('create', 'TestController@createNewTest')->name('tests.create');
    Route::post('create', 'TestController@create')->name('tests.create.post');

    Route::get('{test}', 'TestController@landing')->name('tests.landing');
    Route::get('{test}/manage', 'TestController@manage')->name('tests.manage');

    Route::get('{test}/attempt', 'TestController@attempt')->name('tests.attempt');
    Route::get('{test}/take/{attempt}', 'TestController@take')->name('tests.take');
    Route::post('{test}/response', 'TestController@recordResponse')->name('tests.response.post');
    Route::post('{test}/submit/{attempt}', 'TestController@submit')->name('tests.submit.post');
});

// ## Quizzes
Route::group(['prefix' => 'quiz', 'middleware' => ['auth']], function() {
    Route::get('/', 'QuizController@index')->name('quiz');
    Route::get('take/{chapter?}', 'QuizController@take')->name('quiz.take');
    Route::post('attempt', 'QuizController@attempt')->name('quiz.attempt');
});

// ## Admin
Route::group(['middleware' => ['role:Admin', 'auth'], 'prefix' => 'console'], function() {
    Route::get('/', 'AdminController@dashboard')->name('admin');
    Route::get('/search', 'AdminController@search')->name('admin.search');
    Route::get('/contact/{id?}','ContactController@admin')->name('admin.contact');
    Route::get('/homepage', 'HomeController@edit')->name('admin.general.homepage');
    Route::post('/homepage', 'HomeController@save')->name('admin.general.homepage.post');

    Route::group(['middleware' => ['can:Can manage users']], function() {
        Route::get('users', 'Users\UserController@index')->name('admin.user.index');
        Route::get('user/{id}', 'Users\UserController@getUser')->name('admin.user')->where('id', '[0-9]+');
        Route::post('user/update', 'Users\UserController@postUser')->name('admin.user.post');
        Route::delete('user/role/remove', 'Users\PermissionsController@deleteUserRole')->name('admin.user.role.delete');
        Route::post('user/role/grant', 'Users\PermissionsController@postUserRole')->name('admin.user.role.post');
        Route::post('user/permission/grant', 'Users\PermissionsController@postUserPermission')->name('admin.user.permission.post');
        Route::post('user/lock', 'Users\UserController@lockAccount')->name('admin.user.lock.post');
        Route::post('user/unlock', 'Users\UserController@unlockAccount')->name('admin.user.unlock.post');
        Route::post('user/reset', 'Users\UserController@resetPassword')->name('admin.user.reset-password');
    });

    Route::group(['middleware' => ['can:Can manage roles']], function() {
        Route::get('user/roles/{id?}', 'Users\PermissionsController@getRoles')->name('admin.user.roles')->where('id', '[0-9]+');
        Route::post('user/roles', 'Users\PermissionsController@postRole')->name('admin.user.roles.post');
        Route::delete('user/roles', 'Users\PermissionsController@deleteRole')->name('admin.user.roles.delete');
    });

    Route::group(['middleware' => ['can:Can write content'], 'prefix' => 'content'], function() {
        Route::get('pages', 'ContentController@adminPages')->name('admin.content.pages');
        Route::post('page', 'ContentController@savePage')->name('admin.content.page.post');
        Route::get('page/{page?}', 'ContentController@adminPage')->name('admin.content.page');

        Route::get('links/{link?}', 'ContentController@adminLinks')->name('admin.content.links');
        Route::post('links', 'ContentController@saveLink')->name('admin.content.link.post');
        Route::delete('link', 'ContentController@deleteLink')->name('admin.content.link.delete');
    });

    Route::group(['prefix' => 'emailer', 'middleware' => ['role:Admin', 'auth']], function() {
        Route::get('/', 'EmailManagerController@getCampaignManager')->name('admin.emailer');
        Route::get('/manage/{key}', 'EmailManagerController@getSpecificEmailKind')->name('admin.emailer.specific');
        Route::post('/manage/{key}', 'EmailManagerController@postSendSpecificEmail')->name('admin.emailer.send');
        Route::post('/manage/{key}/preview', 'EmailManagerController@preview')->name('admin.emailer.preview');
    });

    Route::resources([
        'books' => 'BookController',
        'answers' => 'AnswerController'
    ]);

    Route::get('books/{book}/chapters', 'ChapterController@index')->name('chapters.index');
    Route::get('books/{book}/chapters/{chapter}', 'ChapterController@show')->name('chapters.show');
    Route::post('/books/{book}/chapters', 'ChapterController@store')->name('chapters.store');
    Route::get('books/{book}/chapters/{chapter}/edit', 'ChapterController@edit')->name('chapters.edit');
    Route::put('books/{book}/chapters/{chapter}', 'ChapterController@update')->name('chapters.update');
    Route::delete('books/{book}/chapters/{chapter}', 'ChapterController@destroy')->name('chapters.destroy');

    Route::get('chapters/{chapter}/questions', 'QuestionController@index')->name('questions.index');
    Route::get('chapters/{chapter}/questions/create', 'QuestionController@create')->name('questions.create');
    Route::post('chapters/{chapter}/questions', 'QuestionController@store')->name('questions.store');
    Route::get('chapters/{chapter}/questions/{question}', 'QuestionController@show')->name('questions.show');
    Route::get('chapters/{chapter}/questions/{question}/edit', 'QuestionController@edit')->name('questions.edit');
    Route::put('chapters/{chapter}/questions/{question}', 'QuestionController@update')->name('questions.update');
    Route::delete('chapters/{chapter}/questions/{question}', 'QuestionController@destroy')->name('questions.destroy');
});

// Email
Route::group(['prefix' => 'emails'], function() {
    Route::group(['prefix' => 'mailgun'], function() {
        Route::post('/unsubscribe', 'EmailedController@mailgunUnsubscribe');
    });
});

// ## CMS?
Route::get('{page}', 'ContentController@page')->name('content');

app/Models/Book.php
<?php

namespace CHMSSP\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title',
    ];

    public function chapters() {
        return $this->hasMany(Chapter::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace CHMSSP\Http\Controllers;

use CHMSSP\Models\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    // Limit all book functions to those who can manage books
    public function __construct() {
        $this->middleware('can:manage books');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.books.books', [
            'books' => Book::with('chapters')->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required'
        ]);

        $book = Book::create([
            'title' => $request->get('title')
        ]);

        return redirect(route('chapters.index', ['book' => $book->id]))->withSuccess("We've created a new book! Now we need to add a few chapters.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \CHMSSP\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        return redirect(route('chapters.index', ['book' => $book->id]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \CHMSSP\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        return view('admin.books.manage', [
            'book' => $book,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \CHMSSP\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $this->validate($request, [
            'title' => 'required'
        ]);

        $book->update([
            'title' => $request->get('title'),
        ]);

        return redirect(route('books.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \CHMSSP\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();

        return redirect(route('books.index'))->withSuccess("It's Gone!");
    }
}

resources/views/admin/books/books.blade.php
@extends('layouts.admin')

@section('title')
    Books
@endsection

@section('content')
    <div class="row">
        <div class="col-md-8">
            <table class="table table-striped">
                <tbody>
                    @foreach($books as $book)
                        <tr>
                            <th><a href="{{ route('books.show', ['book' => $book->id]) }}">{{ $book->title }}</a></th>
                            <td><a href="{{ route('chapters.index', ['book' => $book->id]) }}">{{ $book->chapters->count() }} {{ str_plural('Chapter', $book->chapters->count()) }}</a></td>
                            <td>
                                <form action="{{ route('books.destroy', ['book' => $book->id]) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <div class="btn-group btn-group-sm">
                                        <a href="{{ route('books.edit', ['book' => $book->id]) }}" class="btn btn-outline-secondary btn-sm">Manage</a>
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <div class="card card-block">
                <h2>Create</h2>
                <form action="{{ route('books.store') }}" method="post">
                    <div class="form-group">
                        <label for="title">Book Title</label>
                        <input type="text" name="title" id="title" class="form-control">
                    </div>
                    <div class="form-group">
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

@endsection

resources/views/admin/books/manage.blade.php
@extends('layouts.admin')

@section('title')
    Update {{ $book->title }}
@endsection

@section('content')
    <div class="row">
        <div class="offset-md-3 col-md-6">
            <form class="card card-block" action="{{ route('books.update', ['book' => $book->id]) }}" method="post">
                <div class="form-group">
                    <label for="title">Book Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ $book->title }}">
                </div>
                <div class="form-group">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')

@endsection